sudo: false
language: cpp
dist: trusty
addons:
  apt:
    packages:
      - clang-3.8
      - clang-format-3.8
      - clang-tidy-3.8
      - cppcheck
      - openmpi-bin
      - libopenmpi-dev
before_install:
  - wget http://www.cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz
install:
  - tar -xf cmake-3.7.2-Linux-x86_64.tar.gz
  - export PATH="${PWD}/cmake-3.7.2-Linux-x86_64/bin:${PATH}"
  - pip install --user flake8
  - git config --global clangformat.binary clang-format-3.8
env:
  matrix:
    - BUILD_MATRIX_ENTRY=format
    - BUILD_MATRIX_ENTRY=analyze
    - BUILD_MATRIX_ENTRY=check
script:
  - ${TRAVIS_BUILD_DIR}/scripts/travis/run.sh

