version: 2
jobs:
  build:
    working_directory: /home/adios2/hidecirclesource
    docker:
      - image: scottwittenburg/adios:adios2testing
    parallelism: 2
    steps:
      - checkout
      - run:
        name: Run dashboard scripts
        type: shell
        command: |
          circleci tests glob "scripts/dashboard/circle_*.cmake" | circleci tests split | xargs bash scripts/dashboard/runOnCircle.sh
