version: 2
jobs:
  build:
    working_directory: /home
    docker:
      - image: scottwittenburg/adios:adios2testing
    steps:
      - checkout
      - run:
          name: Run dashboard scripts
          command: 'cd /home/adios2 && bash adios2/scripts/dashboard/runOnCircle.sh'
